todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('users/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
    path('user_profile/', include('user_profile.urls')),
]

todo/user_profile/urls.py
from django.urls import path
from .views import user_profile


app_name = 'user_profile'

urlpatterns = [
    path('<str:username>/', user_profile, name='user_profile'),
]

todo/users/urls.py
from django.urls import path
from .views import register_user, login_user, logout_user

app_name = 'users'

urlpatterns = [
    path('register/', register_user, name='register_user'),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
]

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    
    {% block head %}{% endblock %}

    <link rel="stylesheet" href="{% static 'css/styles.css'%}" type="text/css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}    
</body>
</html>

todo/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Главная{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

<div class="bg_sidebar">
    {% include 'sidebar.html' %}
</div>


<div class="wrapper">
    <div class="left_block">
        {% include 'index_utils/first_col.html' %}
    </div>

    <div class="right_block">
        {% include 'index_utils/second_col.html' %}
    </div>
</div>
{% endblock %}

todo/templates/sidebar.html
{% load static %}

<!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
      <div class="position-sticky">
        <img
            src="{% static 'img/full_logo.png' %}"
            height="130"
            width="130"
            class="logo_img"
          />
        <div class="list-group list-group-flush mx-3 mt-4">
          <a
            href="/"
            class="list-group-item list-group-item-action py-2 ripple"
            aria-current="true"
          >
            <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Мои задачи</span>
          </a>
          <a href="" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fas fa-chart-area fa-fw me-3"></i><span>Календарь</span>
          </a>
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-lock fa-fw me-3"></i><span>Password</span></a
          >
        </div>
      </div>
    </nav>
    <!-- Sidebar -->
  
    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button data-mdb-button-init
          class="navbar-toggler"
          type="button"
          data-mdb-collapse-init
          data-mdb-target="#sidebarMenu"
          aria-controls="sidebarMenu"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
  
        <!-- Brand -->
        <a class="navbar-brand" href="/">
          <img
            src="{% static 'img/logo.png' %}"
            height="25"
            alt="MDB Logo"
            loading="lazy"
          />
        </a>
        <!-- Search form -->
          {% include 'tasks/search/search.html' %}
        <!-- Right links -->
        <ul class="navbar-nav ms-auto d-flex flex-row">
          <!-- Profile -->
          <div class="dropdown">
            <a href="#">
              <img class="profile_img" src="{% static 'img/profile.png' %}">
            </a>
            <div class="dropdown-content rounded">
              <a href="{% url 'user_profile:user_profile' request.user.username %}">Профиль</a>
              <a href="{% url 'users:logout_user' %}">Выйти</a>
            </div>
          </div>
        </ul>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
  </header>
  <!--Main Navigation-->
  
  <!--Main layout-->
  <main style="margin-top: 70px;">
    <div class="container"></div>
  </main>
  <!--Main layout-->