todo/tasks/urls.py
from django.urls import path
from .views import *


app_name = 'tasks'


urlpatterns = [
    path('my_tasks/', my_tasks, name='my_tasks'),
    path('task/<str:username>/<str:task_id>/', get_task, name='get_task'),
    path('delete_task/<str:task_id>/', delete_task, name='delete_task'),
    path('all_tasks/', all_tasks, name='all_tasks'),
    path('all_subtasks/', all_subtasks, name='all_subtasks'),
    path('task/<str:username>/<str:task_id>/add_subtask/', add_subtask, name='add_subtask'),
    path('delete_subtask/<int:subtask_id>/', delete_subtask, name='delete_subtask'),
    path('search_tasks/', search_tasks, name='search_tasks')
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('users/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
    path('user_profile/', include('user_profile.urls')),
]

todo/user_profile/urls.py
from django.urls import path
from .views import user_profile


app_name = 'user_profile'

urlpatterns = [
    path('<str:username>/', user_profile, name='user_profile'),
]

todo/user_profile/models.py
from django.db import models

# Create your models here.

todo/user_profile/forms.py
from django import forms
from django.contrib.auth import get_user_model

class UpdateUserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].required = False

    class Meta:
        model = get_user_model()
        fields = [
            'username', 'first_name', 
            'last_name', 'email', 
            'password'
        ]
        labels = {
            'password': 'Новый пароль'
        }
        
        

todo/user_profile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from .statistics import Statistics
from .forms import UpdateUserForm


@login_required
def user_profile(request, username):
    user = request.user
    if request.method == 'POST':
        form = UpdateUserForm(data=request.POST, instance=user)
        if form.is_valid():
            user = form.save()
            if 'password' in request.POST:
                user.set_password(request.POST['password'])
            user.save()
            update_session_auth_hash(request, user)
            return redirect(request.path)
    
    if not user.is_authenticated:
        return redirect('users:register_user')
    
    statistics = Statistics(user)
    context = {
        'tasks': {
            'all_tasks': statistics.count_tasks(),
            'count_done_tasks': statistics.count_tasks(completed=True),
            'not_done_tasks': statistics.count_tasks(completed=False),
            'most_subtasks': statistics.most_subtasks(),
            'count_overdue_tasks': statistics.count_overdue_tasks(),
        },
        'subtasks': {
            'all_subtasks': statistics.all_subtasks(),
            'done_subtasks': statistics.all_subtasks(completed=True),
            'not_done_subtasks': statistics.all_subtasks(completed=False),
        },
        'form': UpdateUserForm()
    }


    return render(request, 'user_profile/user_profile.html', context=context)

todo/templates/user_profile/carousel.html
{% load static %}

<div id="carouselExampleCaptions" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        {% if request.user.task.exists %}
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        {% endif %}
    </div>
    <div class="carousel-inner rounded">
      <div class="carousel-item active rounded">
        <img src="{% static 'img/all_tasks.png' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block background-carousel-text rounded">
            <h5>Список всех задач</h5>
            <p>Взгляните на список всех своих задач, чтобы ничего не забыть.</p>
            <p>
                <a class="link-info text-decoration-none"
                  href="{% url 'tasks:all_tasks' %}">
                    *клик*
                </a>    
            </p> 
        </div>
      </div>
      <div class="carousel-item rounded">
        <img src="{% static 'img/all_subtasks.png' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block background-carousel-text rounded">
            <h5>Список всех подзадач</h5>
            <p>Взгляните на список всех своих подзадач, чтобы знать к каким задачам они относятся.</p>
             <p>
                <a class="link-info text-decoration-none"
                  href="{% url 'tasks:all_subtasks' %}">
                    *клик*
                </a>    
            </p> 
        </div>
      </div>
      {% if request.user.task.exists %}
        <div class="carousel-item rounded">
          <img src="{% static 'img/most_subtasks.png' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block background-carousel-text rounded">
            <h5>Задача с наибольшим числом подзадач</h5>
              <p>
                  <a class="link-info text-decoration-none" href="{% url 'tasks:get_task' request.user.username tasks.most_subtasks.pk %}">
                      *клик*
                  </a>          
              </p>
          </div>
        </div>
      {% endif %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

todo/templates/user_profile/diag_subtasks.html
<script src="https://www.google.com/jsapi"></script>
  <script>
   google.load("visualization", "1", {packages:["corechart"]});
   google.setOnLoadCallback(drawChart);
   function drawChart() {
    var data = google.visualization.arrayToDataTable([
     ['Статус', 'Количество'],
     ['Выполненных', '{{ subtasks.done_subtasks }}'],
     ['Не выполненных', '{{ subtasks.not_done_subtasks }}'],
    
    ]);
    var options = {
     title: 'Всего подзадач: {{ subtasks.all_subtasks }}',
     is3D: true,
    };
    var chart = new google.visualization.PieChart(document.getElementById('air_subtasks'));
     chart.draw(data, options);
   }
</script>

todo/templates/user_profile/diag_tasks.html
<script src="https://www.google.com/jsapi"></script>
  <script>
   google.load("visualization", "1", {packages:["corechart"]});
   google.setOnLoadCallback(drawChart);
   function drawChart() {
    var data = google.visualization.arrayToDataTable([
     ['Статус', 'Количество'],
     ['Выполненных', '{{ tasks.count_done_tasks }}'],
     ['Не выполненных', '{{ tasks.not_done_tasks }}'],
    
    ]);
    var options = {
     title: 'Всего задач: {{ tasks.all_tasks }}',
     is3D: true,
    };
    var chart = new google.visualization.PieChart(document.getElementById('air_tasks'));
     chart.draw(data, options);
   }
</script>

todo/templates/user_profile/profile_left_col.html
{% load static %}
{% load user_profile %}

<div class="container page-todo bootstrap snippets bootdeys">

    <div class="task-list main_text">
        <h3>Мои данные</h3>
    </div>

    <div class="stats">{% include 'user_profile/carousel.html' %}</div>

    <div>
        <div class="dashboard rounded profile_span">
            <span class="dashboard span rounded">Личные данные</span>
        </div>

        <div class="col-sm-auto stats">
            <br />
            <hr class="horizontal-gradient" />
            <form method="post">
                {% csrf_token %} 
                
                {% for row in form %}
                    <div class="form-group">
                        <label for="{{ row.name }}">{{ row.label }}</label>
                        <input
                            value="{% user_value request.user row %}"
                            class="form-control"
                            name="{{ row.name }}"
                            type="{{ row.widget_type }}"
                            placeholder="{% if row.name == 'days_left' %}{{ task.days_left }}{% else %}{{ task.creation_d }}{% endif %}"
                        />
                    </div>

                    <br />
                {% endfor %}
                <button
                    id="btn_change"
                    onclick="confirm_change();"
                    type="button"
                    class="btn btn-outline-warning">
                    Сохранить изменения
                </button>
            </form>
        </div>
    </div>

    <br>

    <div>
        <div class="dashboard rounded profile_span">
            <span class="dashboard span rounded">Статистика</span>
        </div>

        <div class="col-sm-auto stats">
            <br />

            <hr class="horizontal-gradient" />

            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <h3>Задачи</h3>
                        <div id="air_tasks" style="width: 100%; height: 495px">
                            {% include 'user_profile/diag_tasks.html' %}
                        </div>
                    </div>
                    <div class="col-sm">
                        <h3>Подзадачи</h3>
                        <div
                            id="air_subtasks"
                            style="width: 100%; height: 495px"
                        >
                            {% include 'user_profile/diag_subtasks.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function confirm_change(){
        var r = confirm("Вы уверены что хотите изменить свои данные?");
        if (r == true) {
            const bt = document.getElementById('btn_change');
            bt.setAttribute('type', 'submit');
        }
    }
</script>

todo/templates/user_profile/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Мой профиль{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

<div class="bg_sidebar">
    {% include 'sidebar.html' %}
</div>

<div class="user_profile">
    {% include 'user_profile/profile_left_col.html' %}
</div>
{% endblock %}