todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('users/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
    path('user_profile/', include('user_profile.urls')),
]

todo/users/urls.py
from django.urls import path
from .views import register_user, login_user, logout_user

app_name = 'users'

urlpatterns = [
    path('register/', register_user, name='register_user'),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
]

todo/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(), label='Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Повтор пароля')

    class Meta:
        model = get_user_model()
        fields = ['username','email','password1','password2'] 
        labels = {
            'username': 'Имя',
            'email': 'Электронный адрес',
        }
        help_texts = {
            'username': 'Ivan123',
            'email': 'ivan-123@todo.com',
        }
        


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=100, 
        label='Имя пользователя или email',
        help_text='Ivan123 / ivan-123@todo.com')
        
    password = forms.CharField(widget=forms.PasswordInput(), label='Пароль')
    
    class Meta:
        model = get_user_model()

todo/users/views.py
from django.http import HttpResponse, HttpResponsePermanentRedirect, HttpResponseRedirect
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from django.contrib import messages
from .forms import RegisterForm, LoginForm


def register_user(request) -> HttpResponse:
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            return render(request, 'users/login.html')
            
    form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, 'users/register.html', context=context)


def login_user(request) -> HttpResponse:
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.data['username']
            password = form.data['password']
            user = get_user_model().objects.filter(Q(username=username) | Q(email=username))
            
            if user.exists():
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('index:index')
        return redirect(request.path)

    form = LoginForm()
    context = {
        'form': form
    }
    return render(request, 'users/login.html', context=context)


def logout_user(request) -> HttpResponseRedirect | HttpResponsePermanentRedirect:
    logout(request)
    return redirect('users:login_user')

todo/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Вход в систему{% endblock %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-4">
                            <h2 class="text-uppercase text-center mb-5 text-muted">Вход в аккаунт</h2>
                            <form method="post">
                                {% csrf_token %}
                                
                                {% for f in form %}
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <input type="{{ f.widget_type }}" id="form{{ f.name }}" class="form-control form-control-lg" name="{{ f.name }}" id="{{ f.name }}" placeholder="{{ f.help_text }}"/>
                                        <label class="form-label" for="form{{ f.name }}">{{ f.label }}</label>
                                    </div>
                                {% endfor %}

                                <div class="d-flex justify-content-center">
                                    <button  type="submit" data-mdb-button-init
                                        data-mdb-ripple-init class="my_btn gradient-custom-4">Войти
                                    </button>
                                </div>

                                <p class="text-center text-muted mt-5 mb-0">Ещё нет аккаунта? <a href="{% url 'users:register_user' %}"
                                    class="fw-bold text-body"><u>Создайте здесь</u></a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

todo/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-4">
                            <h2 class="text-uppercase text-center mb-5 text-muted">Создайте аккаунт</h2>
                            <form method="post">
                                {% csrf_token %}
                                
                                {% for f in form %}
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <input type="{{ f.widget_type }}" id="form{{ f.name }}" class="form-control form-control-lg" name="{{ f.name }}" id="{{ f.name }}" placeholder="{{ f.help_text }}"/>
                                        <label class="form-label" for="form{{ f.name }}">{{ f.label }}</label>
                                    </div>
                                {% endfor %}

                                <div class="d-flex justify-content-center">
                                <button  type="submit" data-mdb-button-init
                                    data-mdb-ripple-init class="my_btn gradient-custom-4">Регистрация</button>
                                </div>

                                <p class="text-center text-muted mt-5 mb-0">Уже есть аккаунт? <a href="{% url 'users:login_user' %}"
                                    class="fw-bold text-body"><u>Войдите здесь</u></a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}