todo/tasks/urls.py
from django.urls import path
from .views import *


app_name = 'tasks'


urlpatterns = [
    path('my_tasks/', my_tasks, name='my_tasks'),
    path('task/<str:username>/<str:task_id>/', get_task, name='get_task'),
    path('delete_task/<str:task_id>/', delete_task, name='delete_task'),
    path('all_tasks/', all_tasks, name='all_tasks'),
    path('all_subtasks/', all_subtasks, name='all_subtasks'),
    path('task/<str:username>/<str:task_id>/add_subtask/', add_subtask, name='add_subtask'),
    path('delete_subtask/<int:subtask_id>/', delete_subtask, name='delete_subtask'),
    path('search_tasks/', search_tasks, name='search_tasks')
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('users/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
    path('user_profile/', include('user_profile.urls')),
]

todo/tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Task(models.Model):
    IMPORTANCE_CHOICES = {
        ('H', 'Важно'),
        ('M', 'Средне'),
        ('L', 'Не важно'),
    }

    title = models.CharField(max_length=150)
    description = models.CharField(max_length=250)
    user = models.ForeignKey(get_user_model(), related_name='task', on_delete=models.CASCADE, default=None)
    importance = models.CharField(max_length=1,
                  choices=IMPORTANCE_CHOICES,
                  default="L")
    creation_date = models.DateField(auto_now=True)
    due_date = models.DateField(blank=True, null=True)
    days_left = models.IntegerField(blank=True, null=False, default=1)
    completed = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.title[:30]}'
    

class SubTask(models.Model):
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=250)
    creation_date = models.DateField(auto_now=True)
    due_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    parent_task = models.ForeignKey(Task, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return f'SubTask({self.title[:30]}) for Task({self.parent_task.title[:30]})'

todo/tasks/forms.py
from django import forms
from .models import Task, SubTask


class DateInput(forms.DateInput):
    input_type = 'date'


class CreateTaskForm(forms.ModelForm):
    importance = forms.ChoiceField(choices=Task.IMPORTANCE_CHOICES ,label='Важность')

    class Meta:
        model = Task
        fields = ('title', 'description', 'due_date')
        labels = {
            'title': 'Название задачи',
            'description': 'Описание',
            'due_date': 'Планируемая дата выполнения',
            'importance': 'Важность',
        }
        help_texts = {
            'title': 'Пробежать 2 км'
        }


class UpdateTaskForm(forms.ModelForm):
    creation_d = forms.DateField(label='Дата создания', required=False)
    
    class Meta:
        model = Task
        fields = ('title', 'description', 'creation_d', 'due_date', 'importance', 'days_left')
        labels = {
            'title': 'Название задачи',
            'description': 'Описание',
            'due_date': 'Планируемая дата выполнения',
            'days_left': 'Осталось дней',
            'importance': 'Важность',
        }


class CreateSubTaskForm(forms.Form):
    parent_task = forms.ModelChoiceField(queryset=Task.objects.all(), label='Для задачи')
    title = forms.CharField(max_length=150, label='Название подзадачи', help_text='Пробежать 2 км')
    description = forms.CharField(max_length=250, label='Описание')

todo/tasks/views.py
from django.http import HttpResponse, HttpResponsePermanentRedirect, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.db.models import Q
from datetime import date, datetime
from .utils import get_importance
from .forms import CreateTaskForm, UpdateTaskForm, CreateSubTaskForm
from .models import Task, SubTask


@login_required
def my_tasks(request) -> HttpResponse:
    if not request.user.is_authenticated:
        return redirect('users:login_user')
    
    if request.method == 'POST':
        create_task_form = CreateTaskForm(request.POST)
        if create_task_form.is_valid():
            data = create_task_form.cleaned_data
            days_left = data['due_date'] - date.today()
            Task.objects.create(user=request.user, **data, days_left=days_left.days)
        return redirect(request.path) 
    else:
        create_task_form = CreateTaskForm()

    tasks = request.user.task.all()

    for i in range(len(tasks)):
        tasks[i].days_left = (tasks[i].due_date - date.today()).days
        tasks[i].save()
    
    high, middle, low = get_importance(tasks)
    upcoming_tasks = request.user.task.filter(days_left__gte=0).order_by('-due_date')[:5]

    context = {
        'tasks': tasks,
        'create_task_form': create_task_form,
        'H': high,
        'M': middle,
        'L': low,
        'upcoming_tasks': upcoming_tasks,
    }

    return render(request, 'index.html', context=context)


@login_required
def get_task(request, username, task_id) -> HttpResponse:
    if request.user.username != username:
        return redirect('/')
    
    if request.method == 'POST':
        task = Task.objects.get(id=task_id)
        
        request.POST._mutable = True

        if not request.POST['due_date']:
            request.POST['due_date'] = task.due_date
        else:
            request.POST['due_date'] = datetime.strptime(request.POST['due_date'], '%Y-%m-%d')

        request.POST['importance'] = request.POST['importance']
        request.POST['days_left'] = (request.POST['due_date'].date() - date.today()).days
        request.POST['creation_d'] = task.creation_date
        
        update_form = UpdateTaskForm(request.POST, instance=task)

        if update_form.is_valid():
            update_form.save()
            
        return redirect(request.path)

    update_form = UpdateTaskForm()
    
    task = Task.objects.filter(id=task_id, user__username=username)[0]
    subtasks = task.subtask_set.all()

    context = {
        'task': task,
        'update_form': update_form,
        'disable_list': ['creation_d', 'days_left'],
        'due_date': task.due_date.strftime(format='%Y-%m-%d'),
        'subtasks': subtasks,
    }
    
    return render(request, 'tasks/task.html', context=context)


@login_required
def delete_task(request, task_id) -> HttpResponseRedirect:
    task = Task.objects.get(id=task_id)
    task.delete()
    return redirect('/')


@login_required
def search_tasks(request):
    search_query = request.GET.get('search_field')
    if search_query:
        tasks = Task.objects.filter(
            Q(title__icontains=search_query) | Q(description__icontains=search_query),
            user=request.user
        )
    else:
        tasks = Task.objects.filter(user=request.user)

    context = {
        'tasks': tasks.order_by('-creation_date', 'title')
    }

    return render(request, 'tasks/search/search_tasks.html', context)


@login_required
def all_tasks(request):    
    tasks = Task.objects.filter(user=request.user)
    context = {
        'tasks': tasks
    }
    return render(request, 'tasks/all_tasks.html', context=context)


@login_required
def all_subtasks(request):
    subtasks = SubTask.objects.filter(parent_task__user=request.user)
    context = {
        'subtasks': subtasks.order_by('-creation_date', 'parent_task__title')
    }
    return render(request, 'tasks/all_subtasks.html', context=context)

@login_required()
def add_subtask(request, username, task_id) -> HttpResponseRedirect | HttpResponse:
    if request.user.username != username:
        return redirect('/')
    
    if request.method == 'POST':
        form = CreateSubTaskForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            
            SubTask.objects.create(
                parent_task=data['parent_task'], 
                title=data['title'],
                description=data['description'],
            )
        
        return redirect(
            'tasks:get_task', 
            username=username,
            task_id=task_id
        )

    form = CreateSubTaskForm()
    
    user_tasks = Task.objects.filter(user=request.user)
    context = {
        'form': form,
        'user_tasks': user_tasks,
        'task_id': int(task_id)
    }

    return render(request, 'tasks/add_subtask.html', context=context)


@login_required
def delete_subtask(request, subtask_id) -> HttpResponseRedirect:
    subtask = SubTask.objects.get(id=subtask_id)
    subtask.delete()
    return redirect(request.META.get('HTTP_REFERER'))

todo/templates/tasks/add_subtask.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Добавить подзадачу{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

<div class="bg_sidebar">
    {% include 'sidebar.html' %}
</div>


<div class="wrapper">
    <div class="left_block">
        <div class="container page-todo bootstrap snippets bootdeys">
            <div class="col-sm-auto tasks rounded">
                <div class="task-list">
                    <h2>Добавить подзадачу</h2>
                    
                    <form method="post">
                        {% csrf_token %}
            
                        {% for i in form %}
                            {% if i.name == 'description' %}
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">{{ i.label }}</label>
                                <textarea name="{{ i.name }}" class="form-control" id="{{ i.name }}" rows="3"></textarea>
                              </div>
                            
                            {% elif i.name == 'parent_task' %}
                                <label for="{{ i.name }}">{{ i.label }}</label>
                                <select name="{{ i.name }}" class="form-select" aria-label="Default select example">
                                    <!-- <option value="{{ task.importance }}">{{ task.get_importance_display }}</option> -->
                                    {% for t in user_tasks %}
                                        <option value="{{ t.id }}" {% if t.id == task_id %}selected{% endif %}>{{ t.title }} {{ t.get_importance_display }}</option>
                                    {% endfor %}
                                </select>
                            
                            {% else%}
                            <div class="form-group">
                                <label for="{{ i.name }}">{{ i.label }}</label>
                                <input name="{{ i.name }}" type="{{ i.widget_type }}" class="form-control" id="{{ i.name }}">
                            </div>
                            {% endif %}

                            <br>
                        {% endfor %}
                        <button type="submit" class="btn btn-outline-success">Добавить</button>
                    </form>
    
                    <div class="clearfix"></div>	 
                </div>       	
            </div>		
        </div>
    </div>

    <div class="right_block">
    </div>
</div>
{% endblock %}

todo/templates/tasks/all_subtasks.html
{% extends 'base.html' %} 

{% load static %} 

{% block title %}Мои модзадачи{% endblock %}

{% block head %}{% endblock %} 

{% block content %}
<div class="bg_sidebar">
    {% include 'sidebar.html' %}
</div>

<div class="wrapper">
    <div class="left_block">
        <div class="container page-todo bootstrap snippets bootdeys">
            <div class="col-sm-auto tasks rounded">
                <div class="task-list">
                    <h2 class="text-center">Подзадачи</h2>
                    <br/>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm">
                                <span class="activity-done"
                                    >Всего: {{ subtasks|length }}</span
                                >
                            </div>
                            {% if subtasks|length > 0 %}
                                <div class="col-sm-3">Выполнена:</div>
                            {% endif %}
                        </div>

                        {% for sub in subtasks %}
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div
                                        class="d-flex justify-content-between align-items-center activity"
                                    >
                                        <div class="icons">
                                            <i class="fa fa-search"></i
                                            ><i class="fa fa-ellipsis-h"></i>
                                        </div>
                                    </div>
                                    <div class="mt-3 custom-width">
                                        <ul class="list">
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col">
                                                        <li class="d-flex justify-content-between">
                                                            <div
                                                                class="d-flex flex-row align-items-center"
                                                            >
                                                                <i
                                                                    class="fa fa-check-circle checkicon"
                                                                ></i>
                                                                <div class="ml-2">
                                                                    <p class="text-info">
                                                                        Родительская задача: 
                                                                        <a href="{% url 'tasks:get_task' request.user.username sub.parent_task.id %}">
                                                                            {{ sub.parent_task }}
                                                                        </a>
                                                                    </p>

                                                                    <h6 class="mb-1">
                                                                        {{ sub.title }}
                                                                    </h6>
                                                                    <div class="box text-black-50">
                                                                        <div>
                                                                            <i class="fa fa-calendar-o"></i>
                                                                            <span class="ml-2">{{ sub.description }}</span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="d-flex flex-row align-items-center">
                                                                <div class="d-flex flex-column">
                                                                    <span class="date-time">
                                                                        {% if sub.completed%}
                                                                            Да
                                                                        {% else %}
                                                                            Нет
                                                                        {% endif %}
                                                                    </span>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </div>
                                                    <div class="col-1 delete_all_sub">
                                                        <a href="#" onclick="confirm_delete_sub('{{ sub.id }}');">
                                                            <img 
                                                                class="delete" 
                                                                src="{% static 'svg/delete.svg' %}"
                                                            />
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            <script>
                function confirm_delete_sub(subtask_id) {
                    var r = confirm("Удалить подзадачу?");
                    {
                        if (r == true) {
                            window.location.href =
                                "{% url 'tasks:delete_subtask' 0 %}".replace(
                                    "0",
                                    subtask_id
                                );
                        }
                    }
                }
            </script>
        </div>
    </div>
</div>
{% endblock %}

todo/templates/tasks/task.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Таска{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

<div class="bg_sidebar">
    {% include 'sidebar.html' %}
</div>


<div class="wrapper">
    <div class="left_block">
        {% include 'tasks/task_first_col.html' %}
    </div>

    <div class="right_block">
        {% include 'tasks/task_second_col.html' %}
    </div>
</div>
{% endblock %}

todo/templates/tasks/task_first_col.html
<div class="container page-todo bootstrap snippets bootdeys">
    <div class="col-sm-auto tasks rounded">
        <div class="task-list">
            <h2>Задача</h2>
            <form method="post">
                {% csrf_token %}
    
                {% for i in update_form %}
                    {% if i.name == 'description' %}
                        <div class="form-group">
                            <label for="exampleFormControlTextarea1">{{ i.label }}</label>
                            <textarea  name="{{ i.name }}" class="form-control" id="{{ i.name }}" rows="3">{{ task.description }}</textarea>
                        </div>
                        

                    {% elif i.name in disable_list %}
                        <div class="form-group">
                            <label for="{{ i.name }}">{{ i.label }}</label>
                            <input disabled
                                    class="form-control"
                                    name="{{ i.name }}" 
                                    type="{% if i.widget_type != 'number' %}{{ i.widget_type }}{% endif %}" 
                                    placeholder="{% if i.name == 'days_left' %}{{ task.days_left }}{% else %}{{ task.creation_d }}{% endif %}">
                        </div>
                    {% elif i.name != 'importance' %}
                        <div class="form-group">
                            <label for="{{ i.name }}">{{ i.label }}</label>
                            <input  value="{{ task.title }}"
                                    name="{{ i.name }}" 
                                    min="{% now 'Y-m-d' %}" 
                                    type="{{ i.widget_type }}" 
                                    class="form-control" 
                                    id="{{ i.name }}" 
                                    placeholder="{{ i.help_text }}">
                        </div>
    
                    {% else %}
                        <label for="{{ i.name }}">{{ i.label }}</label>
                        <select name="{{ i.name }}" class="form-select" aria-label="Default select example">
                            <option value="{{ task.importance }}"> {{ task.get_importance_display }}</option>
                            <option value="H">Важно</option>
                            <option value="M">Средне</option>
                            <option value="L">Не важно</option>
                        </select>
                    
                    {% endif %}
                    
                    <br>
                {% endfor %}
                
                <div class="container">
                    <div class="row">
                      <div class="col">
                        <button type="submit" class="btn btn-outline-warning">Изменить</button>
                      </div>
                      <div class="col-6">
                      </div>
                      <div class="col-2 right-float">
                        <a onclick="confirm_delete();">
                            <button type="button" class="btn btn-outline-danger">Удалить</button>
                        </a>
                      </div>
                    </div>
                </div>
            </form>	
        </div>		
    </div>
</div>

<script>
    document.getElementById("due_date").defaultValue = "{{ due_date }}";
</script>

<script>
    function confirm_delete(){
        var r = confirm("Удалить задачу?");
        if (r == true) {
            window.location.href="{% url 'tasks:delete_task' task.id %}"
        }
    }
</script>

todo/templates/tasks/task_second_col.html
{% load static %}

<div class="container page-todo bootstrap snippets bootdeys">
    <div class="col-sm-auto tasks rounded">
        <div class="task-list">
            <h2>Подзадачи</h2>

            <div class="dashboard">
                <a href="{% url 'tasks:add_subtask' request.user.username task.id %}">
                    <span class="dashboard span">Добавить подзадачу</span>
                </a>
            </div>

            <br>
            <div class="container">
                <div class="row">
                  <div class="col-sm">
                    <span class="activity-done">Всего: {{ subtasks|length }}</span>
                  </div>
                  {% if subtasks|length > 0 %}
                        <div class="col-sm">
                        </div>
                        <div class="col-sm-3">
                            Выполнена:
                        </div>
                        </div>
                    {% endif %}
                </div>
                
            {% for sub in subtasks %}
                <div class="container mt-1">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="d-flex justify-content-between align-items-center activity">
                                <div class="icons"><i class="fa fa-search"></i><i class="fa fa-ellipsis-h"></i></div>
                            </div>
                            <div class="mt-3">
                                <ul class="list list-inline">
                                    <li class="d-flex justify-content-between">
                                        <div class="d-flex flex-row align-items-center"><i class="fa fa-check-circle checkicon"></i>
                                            <div class="ml-2">
                                                <h6 class="mb-0">{{ sub.title }}</h6>
                                                <div class="box text-black-50 ">
                                                    <div><i class="fa fa-calendar-o"></i>
                                                        <span class="ml-2">{{ sub.description }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="d-flex flex-row align-items-center">
                                            <div class="d-flex flex-column mr-2">
                                                <span class="date-time">
                                                    {% if sub.completed %}Да{% else %}Нет{% endif %}
                                                </span>
                                        </div>
                                    </li>
                                </ul>
                                <div class="container">
                                    <div class="row">
                                        <div class="col-sm">
                                        </div>
                                        <div class="col-sm">
                                        </div>
                                        <div class="col-sm-1">
                                            <a href="#" onclick="confirm_delete_sub('{{ sub.id }}');">
                                                <img class="delete" src = "{% static 'svg/delete.svg' %}"/>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <div class="clearfix"></div>	 
        </div>       	
    </div>		
</div>

<script>
    function confirm_delete_sub(subtask_id){
        var r = confirm("Удалить подзадачу?");{
        if (r == true) {
            window.location.href="{% url 'tasks:delete_subtask' 0 %}".replace("0", subtask_id)
        }
    }
}
</script>